var en = {
	//filters
	"Male": "Male",
	"Female": "Female",
	"High potential": "High potential",
	"Medium potential": "Medium potential",
	"Low potential": "Low potential",
	"Depleted potential":"Depleted potential",
	"Exceeded potential":"Exceeded potential",
	"0-15 years old": "0-15 years old",
	"16-40 years old": "16-40 years old",
	"+ than 40 years old": "+ than 40 years old",
	//label potential_ceiling
	"FLOORS":"FLOORS",
	//label identity
	'create traditions':'create traditions.',
	'creates community':'creates community.',
	'feels homely':'feels homely.', 
	'feels quiet':'feels quiet.',
	'feels secured':'feels secured.',
	'has borders':'has borders.',
	'has changed':'has changed.',
	'has culture':'has culture.',
	'has memories':'has memories.',
	'has no activity':'has no activity.',
	'has no recognition':'has no recognition.',
	'has potential':'has potential.',
	'is forgotten':'is forgotten.',
	'is happiness':'is happiness.', 
	'is identity':'is identity.',
	'is moving forward':'is moving forward.', 
	'is my childhood':'is my childhood.',
	'is not active':'is not active.',
	'is not what it was':'is not what it was.', 
	'is obsolete':'is obsolete.',
	'is peaceful':'is peaceful.',
	'is welcoming':'is welcoming.',
	'lacks facilities':'lacks facilities.', 
	'lays on the edge':'lays on the edge.',
	'must change of municipality':'must change of municipality.', 
	'need a school':'need a school.',
	'need more jobs':'need more jobs.',
	'should recover trades':'should recover trades.',
	'will change':'will change.',
	//label perceptions
	'Changing directions':'Changing directions.',
	'Infastructure blocking access to the park':'Infastructure blocking access to the park.',
	'Mass of vehicles in and out of Barcelona':'Mass of vehicles in and out of Barcelona.',
	'The connection with the river is no longer there':'The connection with the river is no longer there.',
	'The height difference and the retaining wall':'The height difference and the retaining wall.',
	'Transit in the main road':'Transit in the main road.',
	//label social_relationships
	'Family members':'Family members: ',
	//label paths
	'Mean of transport':'Mean of transport: ',
	'cycling':'cycling.',
	'private vehicle':'private vehicle.', 
	'public transport':'public transport.',
	'walking':'walking.',
	//label identity
	'Safaretjos is ...':'Safaretjos... ',
	//PopUP potential_ceiling
	"Built floors":"Built floors :",
	"Planned floors":"Planned floors :",
	//PopUp paths
	'On my way':'On my way ',
	'to exercise':'to exercise',
	'to meet friends':'to meet friends', 
	'to school':'to school',
	'to take a walk':'to take a walk',
	"to the doctor\'s":"to the doctor\'s",
	'to the library':'to the library', 
	'to the supermarket':'to the supermarket',
	'to work':'to work',
	//layers potential_ceiling
	"Potential ceiling":"Potential ceiling",
	"Identity":"Identity",
	"Perceptions of borders":"Perceptions of borders",
	"Social networks":"Social networks",
	"Paths":"Paths",
	"Local relationships":"Local relationships",
	"Metropolitan relationships":"Metropolitan relationships",
  //layers perceptions
  "Perceptions": "Perceptions",
	'Darkness':'Darkness',
	'Lost connection':'Lost connection',
	'Noise':'Noise', 
	'Physical border':'Physical border',
	'Vulnerable spaces':'Vulnerable spaces',
	//HOME
	'subtitle':'Cities are becoming really complex organisms.',
	'description':'Massive collection of data can provide a deep insight into the dynamics of the city. In order to understand cities, their governance must consider citizen inputs in the design process. Els Safaretjos, a small neighbourhood of 2000 inhabitants from Santa Coloma de Gramenet (Barcelona) is located at the boundary between four municipalities. It is also a territory within the framework of the Besós River, a metropolitan infrastructure that currently articulates the debate and the need to formulate proposals that come from the administrations as well as from citizens and the academy. The area is currently in a certain urban lack of definition. It has been envisaged as an AREE  (strategic residential area) and now it has come to a halt pending political decisions, both local and supra-local. This research is an attempt to both collect and visualize data from citizens in order to understand the neighbourhood from 7 different dimensions. It provides an observatory on a small scale that can be taken as a basis for future decisions.',
	'go-inside':'Go inside',
	'Safaretjos in 7Dimensions':'Safaretjos in 7Dimensions',
	'go-back':'Go back',
	//CONTENT
	'content_ceiling_title':'How much can Safaretjos grow?',
	'content_ceiling_text':'This map compares urban planning to reality built. Each plot has been classified depending on its buildability potential.\nEven though there are some plots with a buildability index greater than the one established by the urban plan , approximately, xxxxxsq meters are still to be built in this neighbourhood. Therefore, we could expect a great densification in the coming years.'
};