var en = {
	//filters
	"Male": "Male",
	"Female": "Female",
	"High potential": "High potential",
	"Medium potential": "Medium potential",
	"Low potential": "Low potential",
	"Depleted potential":"Depleted potential",
	"Exceeded potential":"Exceeded potential",
	"0-15 years old": "0-15 years old",
	"16-40 years old": "16-40 years old",
	"+ than 40 years old": "+ than 40 years old",
	//label potential_ceiling
	"FLOORS":"FLOORS",
	//label identity
	'create traditions':'create traditions',
	'creates community':'creates community',
	'feels homely':'feels homely', 
	'feels quiet':'feels quiet',
	'feels secured':'feels secured',
	'has borders':'has borders',
	'has changed':'has changed',
	'has culture':'has culture',
	'has memories':'has memories',
	'has no activity':'has no activity',
	'has no recognition':'has no recognition',
	'has potential':'has potential',
	'is forgotten':'is forgotten',
	'is happiness':'is happiness', 
	'is identity':'is identity',
	'is moving forward':'is moving forward', 
	'is my childhood':'is my childhood',
	'is not active':'is not active',
	'is not what it was':'is not what it was', 
	'is obsolete':'is obsolete',
	'is peaceful':'is peaceful',
	'is welcoming':'is welcoming',
	'lacks facilities':'lacks facilities', 
	'lays on the edge':'lays on the edge',
	'must change of municipality':'must change of municipality', 
	'need a school':'need a school',
	'need more jobs':'need more jobs',
	'should recover trades':'should recover trades',
	'will change':'will change',
	//label perceptions
	'Changing directions':'Changing directions',
	'Infastructure blocking access to the park':'Infastructure blocking access to the park',
	'Mass of vehicles in and out of Barcelona':'Mass of vehicles in and out of Barcelona',
	'The connection with the river is no longer there':'The connection with the river is no longer there',
	'The height difference and the retaining wall':'The height difference and the retaining wall',
	'Transit in the main road':'Transit in the main road',
	//label social_relationships
	'Family members':'Family members',
	//label paths
	'Mean of transport':'Mean of transport :',
	'cycling':'cycling',
	'private vehicle':'private vehicle', 
	'public transport':'public transport',
	'walking':'walking',
	//label identity
	'Safaretjos is ...':'Safaretjos is ...',
	//PopUP potential_ceiling
	"Built floors":"Built floors :",
	"Planned floors":"Planned floors",
	//PopUp paths
	'to exercise':'to exercise',
	'to meet friends':'to meet friends', 
	'to school':'to school',
	'to take a walk':'to take a walk',
	"to the doctor\'s":"to the doctor\'s",
	'to the library':'to the library', 
	'to the supermarket':'to the supermarket',
	'to work':'to work',
	//layers potential_ceiling
	"Potential ceiling":"Potential ceiling",
	"Identity":"Identity",
	"Perceptions of borders":"Perceptions of borders",
	"Social networks":"Social networks",
	"Paths":"Paths",
	"Local relationships":"Local relationships",
	"Metropolitan relationships":"Metropolitan relationships",
	//layers perceptions
	'Darkness':'Darkness',
	'Lost connection':'Lost connection',
	'Noise':'Noise', 
	'Physical border':'Physical border',
	'Vulnerable spaces':'Vulnerable spaces',
	//HOME
	'subtitle':'Cities are becoming a really complex organism.',
	'description':'The inhabitants of a city produce a constant flow of data. This data can be visualized and taken as a basis for observation and future decisions. The visualization of this info creates new knowledge about the city and is able to make the invisible visible (create an observatory). Active participation of citizens as well as passively collected data has helped to understand the neighbourhood from 7 dimensions./identify citizens perceptions and barriers in the neighbourhood/different dimensions in the neighbourhood that have question the actual urban plan. This project is focused on the neighborhood of Els Safaretjos in Santa Coloma de Gramenet (Barcelona). It is a territory within the framework of the Besós River, a metropolitan infrastructure that currently articulates the debate and the need to formulate proposals that come from the administrations as well as from citizens and the academy. At the same time, it is eccentric of its city Santa Coloma de Gramenet. The area is in a certain urban lack of definition. It has been envisaged as an AREE  (strategic residential area) and now it has come to a halt pending political decisions, both local and supra-local. The neighborhood of Els Safaretjos is part of District V, which extends over 65 Ha, in which 24,042 people live.',
	'go-inside':'Go inside',
	'Safaretjos in 7Dimensions':'Safaretjos in 7Dimensions',
	'go-back':'Go back'
};