var es = {
	//filters
	"Male": "Hombre",
	"Female": "Mujer",
	"High potential": "Potencial alto",
	"Medium potential": "Potencial medio",
	"Low potential": "Potencial bajo",
	"Depleted potential":"Potencial agotado",
	"Exceeded potential":"Potencial excedido",
	"0-15 years old": "0-15 años",
	"16-40 years old": "16-40 años",
	"+ than 40 years old": "+ de 40 años",
	//label
	"FLOORS":" PLANTAS",
	"Buildable floors":'Plantas edificables: ',
	//label identity
	'create traditions':'crea tradiciones.',
	'creates community':'crea comunidad.',
	'feels homely':'es familiar.', 
	'feels quiet':'es tranquilo.',
	'feels secured':'es seguro.',
	'has borders':'tiene límites.',
	'has changed':'ha cambiado.',
	'has culture':'tiene cultura.',
	'has memories':'tiene memorias.',
	'has no activity':'no tiene actividad.',
	'has no recognition':'no es reconocido.',
	'has potential':'tiene potencial.',
	'is forgotten':'está olvidado.',
	'is happiness':'es felicidad.', 
	'is identity':'es identidad.',
	'is moving forward':'está mejorando.', 
	'is my childhood':'es mi infancia.',
	'is not active':'no es activo.',
	'is not what it was':'no es lo que era.', 
	'is obsolete':'es obsoleto.',
	'is peaceful':'es pacífico.',
	'is welcoming':'es acojedor.',
	'lacks facilities':'necesita equipamientos.', 
	'lays on the edge':'está situado en el límite.',
	'must change of municipality':'tiene que cambiar de municipio.', 
	'need a school':'necesita una escuela.',
	'need more jobs':'necesita puestos de trabajo.',
	'should recover trades':'tendría que recuperar la actividad económica',
	'will change':'cambiará',
	//label perceptions
	'Changing directions':'Cambios de dirección.',
	'Infastructure blocking access to the park':'Infraestructura bloqueando el acceso al parque.',
	'Mass of vehicles in and out of Barcelona':'Masa de vehículos entrando y saliendo de Barcelona.',
	'The connection with the river is no longer there':'Se ha perdido la conexión con el río.',
	'The height difference and the retaining wall':'La diferencia de cota y el muro de contención.',
	'Transit in the main road':'Tránsito en la carretera principal.',
	//label social_relationships
	'Family members':'Miembros de la família: ',
	//label paths
	'Mean of transport':'Medio de transporte: ',
	'cycling':'en bicicleta.',
	'private vehicle':'vehículo privado.', 
	'public transport':'transporte público.',
	'walking':'caminando.',
	//label identity
	'Safaretjos is ...':'Safaretjos... ',
	'Identity:':'Identidad: ',
	//PopUP potential_ceiling
	"Built floors":"Plantas construidas: ",
	"Planned floors":"Plantas según planeamiento: ",
	//PopUp paths
	'On my way':'De camino ',
	'to exercise':'a hacer ejercicio.',
	'to meet friends':'a visitar amigos.', 
	'to school':'a la escuela.',
	'to take a walk':'a dar un paseo.',
	"to the doctor\'s":'al médico.',
	'to the library':'a la biblioteca.', 
	'to the supermarket':'al supermercado.',
	'to work':'al trabajo.',
	//layers potential_ceiling
	"Potential ceiling":"Techo potencial",
	"Identity":"Identidad",
	"Perceptions of borders":"Percepción de fronteras",
	"Social networks":"Redes sociales",
	"Paths":"Recorridos",
	"Local relationships":"Relaciones locales",
	"Metropolitan relationships":"Relaciones metropolitanas",
  	//layers perceptions
  	"Perceptions": "Percepciones",
	'Darkness':'Oscuridad',
	'Lost connection':'Conexión perdida',
	'Noise':'Ruido', 
	'Physical border':'Frontera física',
	'Vulnerable spaces':'Zonas vulnerables',
	//HOME
	'subtitle':'Las ciudades están convirtiéndose en organismos realmente complejos.',
	'description':'Los habitantes de las ciudades producen un flujo constante de datos. La recopilación masiva de estos datos puede proporcionar una visión más profunda de la dinámica de la ciudad. Para comprender las ciudades, su gobierno debe tener en cuenta los aportes de los ciudadanos en el proceso de diseño. Safaretjos es un pequeño barrio de 2000 habitantes de Santa Coloma de Gramenet (Barcelona) situado en el límite entre cuatro municipios. Es un territorio en el marco del río Besós, una infraestructura metropolitana que actualmente articula el debate y la necesidad de formular propuestas que provienen tanto de las administraciones como de los ciudadanos y la academia. El área se encuentra actualmente en una cierta falta de definición urbana. Ha sido concebido como un AREE (área residencial estratégica) y actualmente está a la espera de decisiones políticas, tanto locales como supralocales. Esta investigación se basa en la recopilación y la visualización de datos de los ciudadanos para comprender el vecindario desde 7 dimensiones diferentes. Es un observatorio de la ciudad a pequeña escala que puede tomarse como base para futuras decisiones.',
	'go-inside':'Entrar',
	/*'Safaretjos in 7Dimensions':'Safaretjos en 7Dimensiones',*/
	'go-back':'Atrás',
	//CONTENT
	'Read content':'Leer el contenido',
	'Go to map':'Ir al mapa',
	'content_ceiling_title':'¿Cuánto puede crecer Safaretjos?',
	'content_ceiling_text':'Conocer el estado de la edificabilidad de las ciudades permite identificar aquellas áreas de posible desarrollo. Este mapa es una comparación entre el planeamiento urbanístico y la realidad construida. Cada parcela ha sido clasificada según su potencial de edificabilidad. Las parcelas con un potencial más alto se encuentran junto al río, una zona considerada como un área residencial estratégica que prevé la construcción de 310 viviendas. Aunque hay algunas parcelas con un índice de edificabilidad mayor que el establecido por el planeamiento urbano, aproximadamente, 45.000 metros cuadrados de techo faltan por ser construidos en este vecindario. En consecuencia, podemos esperar una gran densificación del barrio en los próximos años.',
	'content_identity_title':'¿Cómo medir el sentimiento de identidad?',
	'content_identity_text':'Recopilar datos no es solo cuestión de asignar un número a todo. Uno debe ser crítico antes de sacar conclusiones sobre los datos.\n¿Qué es realmente identidad para cada persona? Dado que no existe una respuesta clara, se hicieron varias preguntas a los vecinos para tener una idea de sus sentimientos hacia el vecindario. Cada una de ellas fue respondida con un número en un rango del 0 (muy negativo) al 10 (muy positivo).\n¿Cómo valorarías ...\ntu relación con tus vecinos?\ntu participación en el tejido asociativo del vecindario?\ntu aprecio hacia el vecindario?\ntus experiencias en el vecindario?\nPreguntas abiertas como la forma en que describirían el lugar en pocas palabras también se llevaron a cabo para obtener una mejor comprensión de los números.\nDespués de analizar los casos, se asignó un número promedio de las respuestas obtenidas para visualizar la sensación de identidad en el vecindario.',
	'content_perceptions_title':'¿Existen fronteras invisibles en Safaretjos?',
	'content_perceptions_text':'Los cerebros humanos están constantemente procesando millones de inputs que son generados cada día en las nuevas ciudades dinámicas. Recopilar datos activos basados en percepciones es un avance. Cada persona tiene una percepción diferente del mundo en constante cambio en el que vivimos.\nNo solo los territorios están divididos por los límites municipales. Las consecuencias de las decisiones arquitectónicas también pueden convertirse en fronteras invisibles en la ciudad, lo que puede afectar el comportamiento y las percepciones de sus ciudadanos.\nLos datos han sido recopilados mediante múltiples dibujos generados después de varias discusiones con los vecinos.\nEl mapa convierte lo invisible a visible. En otras palabras, trata de visualizar lo que los vecinos experimentan y perciben a través de sus sentidos.',
	'content_social_title':'¿Es Safaretjos una comunidad?',
	'content_social_text':'Como seres humanos, necesitamos un sentido de pertenencia, ese sentido es lo que nos conecta con muchas de las relaciones que desarrollamos.\nLas comunidades permiten apoyarnos, interactuar, compartir experiencias, construir relaciones valiosas… Todos somos miembros de muchas comunidades (familia, trabajo, vecindario, etc.), y nos movemos constantemente dentro y fuera de ellas dependiendo de la situación.\nEn este caso, el objetivo es identificar si existe una comunidad en Safaretjos. Para responder a esa pregunta, se recopilaron datos sobre las comunidades a las que pertenecían los habitantes del barrio, sobre cuántas personas conocen en el vecindario, qué actividades desarrollan juntos, dónde las realizan y con qué frecuencia.\nEl mapa muestra una red que representa las relaciones sociales dentro del vecindario.',
	'content_paths_title':'¿Cómo se mueven los ciudadanos en Safaretjos?',
	'content_paths_text':'Los humanos estamos constantemente en movimiento. La mayoría de nosotros estaría de acuerdo en que el movimiento es un poderoso signo de la vitalidad humana.\nCon el fin de mapear los flujos de los ciudadanos, se pidió a los vecinos del barrio que dibujaran los caminos que a menudo recorren para realizar sus actividades diarias, así como también el medio de transporte utilizado.\nPor naturaleza, la mayoría de ellos tienden a moverse y pasar la mayor parte del día en Sant Adrià en lugar de hacia Santa Coloma.',
	'content_local_title':'¿Deberían modificarse los límites administrativos?',
	'content_local_text':'Safaretjos es un territorio que se encuentra excéntricamente de su ciudad, Santa Coloma de Gramenet. La mayoría de las instalaciones ubicadas a corta distancia pertenecen a otros municipios.\nNo es fácil encontrar un lugar en las escuelas públicas cercanas al vecindario ya que estas no pertenecen a Santa Coloma. El mismo problema ocurre cuando los ciudadanos necesitan hacer uso de cualquier otro servicio público.\nLos datos que se han recopilado muestran cómo las personas hacen uso de las instalaciones locales independientemente de su municipio.\nEl mapa cuestiona el rol que desempeñan los límites administrativos en el vecindario y propone soluciones tales como acuerdos de uso compartido para escuelas, centros de atención primaria y otros servicios.',
	'content_metro_title':'¿Qué papel juega Safaretjos a escala metropolitana?',
	'content_metro_text':'La situación de Safaretjos es estratégica a escala metropolitana y, más concretamente, en el territorio del Besós. Debido a su capacidad de centralidad y rótula metropolitana se convierte en una pieza central del Plan Besós.\nA fin de visualizar los flujos de los ciudadanos en una escala metropolitana, se preguntó a los vecinos sobre sus movimientos hacia otros municipios por motivos de trabajo, estudios, familia y ocio.',
};