var es = {
	//filters
	"Male": "Hombre",
	"Female": "Mujer",
	"High potential": "Potencial alto",
	"Medium potential": "Potencial medio",
	"Low potential": "Potencial bajo",
	"Depleted potential":"Potencial agotado",
	"Exceeded potential":"Potencial excedido",
	"0-15 years old": "0-15 años",
	"16-40 years old": "16-40 años",
	"+ than 40 years old": "+ de 40 años",
	//label
	"FLOORS":"PLANTAS",
	//label identity
	'create traditions':'crea tradiciones.',
	'creates community':'crea comunidad.',
	'feels homely':'es familiar.', 
	'feels quiet':'es tranquilo.',
	'feels secured':'es seguro.',
	'has borders':'tiene límites.',
	'has changed':'ha cambiado.',
	'has culture':'tiene cultura.',
	'has memories':'tiene memorias.',
	'has no activity':'no tiene actividad.',
	'has no recognition':'no es reconocido.',
	'has potential':'tiene potencial.',
	'is forgotten':'está olvidado.',
	'is happiness':'es felicidad.', 
	'is identity':'es identidad.',
	'is moving forward':'está mejorando.', 
	'is my childhood':'es mi infancia.',
	'is not active':'no es activo.',
	'is not what it was':'no es lo que era.', 
	'is obsolete':'es obsoleto.',
	'is peaceful':'es pacífico.',
	'is welcoming':'es acojedor.',
	'lacks facilities':'necesita equipamientos.', 
	'lays on the edge':'está situado en el límite.',
	'must change of municipality':'tiene que cambiar de municipio.', 
	'need a school':'necesita una escuela.',
	'need more jobs':'necesita puestos de trabajo.',
	'should recover trades':'tendría que recuperar la actividad económica',
	'will change':'cambiará',
	//label perceptions
	'Changing directions':'Cambios de dirección.',
	'Infastructure blocking access to the park':'Infraestructura bloqueando el acceso al parque.',
	'Mass of vehicles in and out of Barcelona':'Masa de vehículos entrando y saliendo de Barcelona.',
	'The connection with the river is no longer there':'Se ha perdido la conexión con el río.',
	'The height difference and the retaining wall':'La diferencia de cota y el muro de contención.',
	'Transit in the main road':'Tránsito en la carretera principal.',
	//label social_relationships
	'Family members':'Miembros de la família: ',
	//label paths
	'Mean of transport':'Medio de transporte: ',
	'cycling':'en bicicleta.',
	'private vehicle':'vehículo privado.', 
	'public transport':'transporte público.',
	'walking':'caminando.',
	//label identity
	'Safaretjos is ...':'Safaretjos... ',
	//PopUP potential_ceiling
	"Built floors":"Plantas construidas: ",
	"Planned floors":"Plantas según planeamiento: ",
	//PopUp paths
	'On my way':'De camino ',
	'to exercise':'a hacer ejercicio.',
	'to meet friends':'a visitar amigos.', 
	'to school':'a la escuela.',
	'to take a walk':'a dar un paseo.',
	"to the doctor\'s":'al médico.',
	'to the library':'a la biblioteca.', 
	'to the supermarket':'al supermercado.',
	'to work':'al trabajo.',
	//layers potential_ceiling
	"Potential ceiling":"Techo potencial",
	"Identity":"Identidad",
	"Perceptions of borders":"Percepción de fronteras",
	"Social networks":"Redes sociales",
	"Paths":"Recorridos",
	"Local relationships":"Relaciones locales",
	"Metropolitan relationships":"Relaciones metropolitanas",
  	//layers perceptions
  	"Perceptions": "Percepciones",
	'Darkness':'Oscuridad',
	'Lost connection':'Conexión perdida',
	'Noise':'Ruido', 
	'Physical border':'Frontera física',
	'Vulnerable spaces':'Zonas vulnerables',
	//HOME
	'subtitle':'Las ciudades están convirtiéndose en organismos realmente complejos.',
	'description':'Traducir al español',
	'go-inside':'Entrar',
	'Safaretjos in 7Dimensions':'Safaretjos en 7Dimensiones',
	'go-back':'Atrás'
};