var es = {
	//filters
	"Male": "Hombre",
	"Female": "Mujer",
	"High potential": "Potencial alto",
	"Medium potential": "Potencial medio",
	"Low potential": "Potencial bajo",
	"Depleted potential":"Potencial agotado",
	"Exceeded potential":"Potencial excedido",
	"0-15 years old": "0-15 años",
	"16-40 years old": "16-40 años",
	"+ than 40 years old": "+ de 40 años",
	//label
	"FLOORS":"PLANTAS",
	//label identity
	'create traditions':'traducir al español',
	'creates community':'traducir al español',
	'feels homely':'traducir al español', 
	'feels quiet':'traducir al español',
	'feels secured':'traducir al español',
	'has borders':'traducir al español',
	'has changed':'traducir al español',
	'has culture':'traducir al español',
	'has memories':'traducir al español',
	'has no activity':'traducir al español',
	'has no recognition':'traducir al español',
	'has potential':'traducir al español',
	'is forgotten':'traducir al español',
	'is happiness':'traducir al español', 
	'is identity':'traducir al español',
	'is moving forward':'traducir al español', 
	'is my childhood':'traducir al español',
	'is not active':'traducir al español',
	'is not what it was':'traducir al español', 
	'is obsolete':'traducir al español',
	'is peaceful':'traducir al español',
	'is welcoming':'traducir al español',
	'lacks facilities':'traducir al español', 
	'lays on the edge':'traducir al español',
	'must change of municipality':'traducir al español', 
	'need a school':'traducir al español',
	'need more jobs':'traducir al español',
	'should recover trades':'traducir al español',
	'will change':'traducir al español',
	//label perceptions
	'Changing directions':'traducir al español',
	'Infastructure blocking access to the park':'traducir al español',
	'Mass of vehicles in and out of Barcelona':'traducir al español',
	'The connection with the river is no longer there':'traducir al español',
	'The height difference and the retaining wall':'traducir al español',
	'Transit in the main road':'traducir al español',
	//label social_relationships
	'Family members':'traducir al español',
	//label paths
	'Mean of transport':'traducir al español',
	'cycling':'traducir al español',
	'private vehicle':'traducir al español', 
	'public transport':'traducir al español',
	'walking':'traducir al español',
	//label identity
	'Safaretjos is ...':'Safaretjos es ...',
	//PopUP potential_ceiling
	"Built floors":"Plantas construidas: ",
	"Planned floors":"Plantas según planeamiento: ",
	//PopUp paths
	'On my way':'De camino a: ',
	'to exercise':'traducir al español',
	'to meet friends':'traducir al español', 
	'to school':'traducir al español',
	'to take a walk':'traducir al español',
	"to the doctor\'s":'traducir al español',
	'to the library':'traducir al español', 
	'to the supermarket':'traducir al español',
	'to work':'traducir al español',
	//layers potential_ceiling
	"Potential ceiling":"Techo potencial",
	"Identity":"Identidad",
	"Perceptions of borders":"Percepción de fronteras",
	"Social networks":"Redes sociales",
	"Paths":"Recorridos",
	"Local relationships":"Relaciones locales",
	"Metropolitan relationships":"Relaciones metropolitanas",
  //layers perceptions
  "Perceptions": "Percepciones",
	'Darkness':'traducir al español',
	'Lost connection':'traducir al español',
	'Noise':'traducir al español', 
	'Physical border':'traducir al español',
	'Vulnerable spaces':'traducir al español',
	//HOME
	'subtitle':'Cities are becoming a really complex organism.--traducir español',
	'description':'Traducir al español',
	'go-inside':'Entrar',
	'Safaretjos in 7Dimensions':'Safaretjos en 7Dimensiones',
	'go-back':'Atrás'
};